version: "3"
services:
    influxdb:
        container_name: influxdb
        restart: always
        build:
            context: ./influxdb/build
            dockerfile: Dockerfile
        environment:
            INFLUXDB_ADMIN_USER: admin-user
            INFLUXDB_ADMIN_PASSWORD: admin-pwd
        volumes:
        # Mount for influxdb data directory and configuration
            - ./influxdb/var/lib:/var/lib/influxdb
            - ./influxdb/etc/influxdb.conf:/etc/influxdb/influxdb.conf     
        ports:
            - 8086:8086
        networks:
            - influxdb-network
            
    chronograf:
        container_name: chronograf
        restart: always
        build:
            context: ./chronograf/build
            dockerfile: Dockerfile
        depends_on:
            - influxdb
        environment:
            INFLUXDB_URL: http://influxdb:8086
            INFLUXDB_USERNAME: admin-user
            INFLUXDB_PASSWORD: admin-pwd
        volumes:
            - ./chronograf/var/lib:/var/lib/chronograf
        ports:
            - 8888:8888
        networks:
            - influxdb-network

networks:
    influxdb-network:
        driver: bridge
